name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: build ingest-common
      run: ./gradlew modules:ingest-common:assemble
    - name: build reindex
      run: ./gradlew modules:reindex:assemble
    - name: lang-mustache
      run: ./gradlew modules:lang-mustache:assemble
    - name: build parent-join
      run: ./gradlew modules:parent-join:assemble

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: test ingest-common
      run: ./gradlew modules:ingest-common:test
    - name: test reindex
      run: ./gradlew modules:reindex:test
    - name: lang-mustache
      run: ./gradlew modules:lang-mustache:test
    - name: test parent-join
      run: ./gradlew modules:parent-join:test
